export default ({
  FETCH_TICKETS_REQUEST: 'FETCH_TICKETS_REQUEST',
  FETCH_TICKETS_SUCCESS: 'FETCH_TICKETS_SUCCESS',
  FETCH_TICKETS_FAILURE: 'FETCH_TICKETS_FAILURE',
  SET_FETCHING: 'SET_FETCHING',
  SET_FILTER: 'SET_FILTER',
  SET_SORTING: 'SET_SORTING'
} as const);
